name: Deploy Sanity Studio

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'studio-telkom/**'  # Hanya trigger saat ada perubahan di folder studio
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'studio-telkom/**'
  workflow_dispatch:  # Memungkinkan trigger manual dari GitHub UI

jobs:
  deploy-studio:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'dev' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.x
        run_install: false
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'pnpm'
        cache-dependency-path: 'studio-telkom/pnpm-lock.yaml'
    
    - name: Install dependencies
      working-directory: ./studio-telkom
      run: pnpm install
    
    - name: Deploy Sanity Studio
      working-directory: ./studio-telkom
      run: npx sanity@latest deploy
      env:
        SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        SANITY_STUDIO_HOSTNAME: ${{ vars.SANITY_STUDIO_HOSTNAME || 'localhost:3333' }}
        SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
        SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
